### ISSUE TITLE
Only show one error if using non-Dotlin primitive type

### ISSUE THREAD

**Issue by eggnstone** [dirtlang/dirt#64]
It looks like the variable type "Char" is not supported:

Kotlin code:
```
class Constants
{
    companion object
    {
        const val C: Char = 'C'
    }
}
```

```
lib\Constants.kt:5:19: error: 'public' property exposes its 'internal' type Char
        const val C: Char = 'C'
                  ^
lib\Constants.kt:5:22: error: cannot access 'Char': it is internal in 'kotlin'
        const val C: Char = 'C'
                     ^
lib\Constants.kt:5:29: error: cannot use Char, use String instead
        const val C: Char = 'C'
                            ^
Exception in thread "main" org.dotlin.compiler.backend.DotlinCompilerError
        at org.dotlin.compiler.backend.steps.src2ir.AnalyzeUtilsKt.throwIfHasErrors(AnalyzeUtils.kt:46)
        at org.dotlin.compiler.backend.steps.src2ir.AnalyzeUtilsKt.throwIfHasErrors(AnalyzeUtils.kt:42)
        at org.dotlin.compiler.backend.steps.src2ir.analyze.DartKotlinAnalyzerReporter.analyzeAndReport(DotlinAnalyzerReporter.kt:70)
        at org.dotlin.compiler.backend.steps.src2ir.SourceToIrKt.loadIr(SourceToIr.kt:105)
        at org.dotlin.compiler.backend.steps.src2ir.SourceToIrKt.sourceToIr(SourceToIr.kt:59)
        at org.dotlin.compiler.KotlinToDartCompiler.compile(KotlinToDartCompiler.kt:93)
        at org.dotlin.compiler.KotlinToDartCompiler.compile$default(KotlinToDartCompiler.kt:83)
        at org.dotlin.compiler.KotlinToDartCompiler.compile(KotlinToDartCompiler.kt:78)
        at org.dotlin.compiler.cli.command.Compile.run(Compile.kt:37)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
        at org.dotlin.compiler.Dotlin.main(Main.kt:26)

```

**Comment by wilkomanger** [comment]
Yeah that's expected behavior, the `cannot use Char, use String instead` is a Dotlin error :+1:

I made the [design decision to simplify the types](https://github.com/dotlin-org/dotlin#primitives), since they have no equivalent in Dart and would hinder interoperability. In short it means `Byte`, `Short`, `Long`, `Float` and `Char` are not available, and `Int` refers to a 64-bit integer.

I do think seeing the errors there that the top 2 should be hidden away
